# --- !Ups

CREATE TABLE "CARTON_HDR" 
   (    "CARTON_NBR" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
    "PKT_CTRL_NBR" VARCHAR2(10 CHAR), 
    "WHSE" VARCHAR2(3 CHAR), 
    "WAVE_NBR" VARCHAR2(12 CHAR), 
    "SEQ_RULE_PRTY" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE, 
    "STAT_CODE" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE, 
    "STAGE_INDIC" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE, 
    "SNGL_SKU_FLAG" VARCHAR2(1 CHAR), 
    "SKU_ID" VARCHAR2(10 CHAR), 
    "CARTON_CREATION_CODE" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE, 
    "PICK_LOCN_ID" VARCHAR2(10 CHAR), 
    "CURR_LOCN_ID" VARCHAR2(10 CHAR), 
    "PREV_LOCN_ID" VARCHAR2(10 CHAR), 
    "DEST_LOCN_ID" VARCHAR2(10 CHAR), 
    "ALT_CARTON_NBR" VARCHAR2(20 CHAR), 
    "SPUR_LANE" VARCHAR2(4 CHAR), 
    "SPUR_POSN" VARCHAR2(4 CHAR), 
    "FIRST_ZONE" VARCHAR2(4 CHAR), 
    "LAST_ZONE" VARCHAR2(4 CHAR), 
    "NBR_OF_ZONES" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE, 
    "TOTAL_QTY" NUMBER(9,2) DEFAULT 0 NOT NULL ENABLE, 
    "CARTON_TYPE" VARCHAR2(3 CHAR), 
    "CARTON_SIZE" VARCHAR2(3 CHAR), 
    "REF_CASE_NBR" VARCHAR2(20 CHAR), 
    "EST_VOL" NUMBER(13,4) DEFAULT 0 NOT NULL ENABLE, 
    "EST_WT" NUMBER(13,4) DEFAULT 0 NOT NULL ENABLE, 
    "ACTL_WT" NUMBER(13,4) DEFAULT 0 NOT NULL ENABLE, 
    "CARTON_NBR_X_OF_Y" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
    "PLT_ID" VARCHAR2(20 CHAR), 
    "PLT_TYPE" VARCHAR2(3 CHAR), 
    "PLT_SIZE" VARCHAR2(3 CHAR), 
    "PLT_NBR_X_OF_Y" NUMBER(7,0) DEFAULT 0 NOT NULL ENABLE, 
    "PLT_SIZE_TYPE" VARCHAR2(3 CHAR), 
    "PROD_VALUE" NUMBER(11,2) DEFAULT 0 NOT NULL ENABLE, 
    "SHPMT_NBR" VARCHAR2(20 CHAR), 
    "TRLR_STOP_SEQ_NBR" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE, 
    "FRT_CHRG" NUMBER(11,2) DEFAULT 0 NOT NULL ENABLE, 
    "BOL" VARCHAR2(20 CHAR), 
    "MANIF_NBR" VARCHAR2(20 CHAR), 
    "TRKG_NBR" VARCHAR2(50 CHAR), 
    "TRLR_NBR" VARCHAR2(12 CHAR), 
    "LOAD_SEQ" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE, 
    "SHIP_VIA" VARCHAR2(4 CHAR), 
    "LABEL_TYPE" VARCHAR2(3 CHAR), 
    "SKU_STAT_CODE" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE, 
    "REPRT_CNT" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE, 
    "TRANS_INVN_TYPE" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE, 
    "OVRSZ_LEN" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE, 
    "CARTON_DIVRT_CODE" VARCHAR2(2 CHAR), 
    "MASTER_PACK_ID" VARCHAR2(20 CHAR), 
    "WAVE_STAT_CODE" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE, 
    "WAVE_SEQ_NBR" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE, 
    "TRLR_ZONE_INDIC" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
    "TRLR_POSN_X_COORD" VARCHAR2(3 CHAR), 
    "TRLR_POSN_Y_COORD" VARCHAR2(3 CHAR), 
    "BPI" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE, 
    "PICK_DLVRY_DURTN" NUMBER(5,2) DEFAULT 0 NOT NULL ENABLE, 
    "IDEAL_PICK_DATE_TIME" DATE, 
    "OUT_OF_ZONE_INDIC" VARCHAR2(1 CHAR), 
    "PKT_CONSOL_ATTR" VARCHAR2(3 CHAR), 
    "PIKR" VARCHAR2(15 CHAR), 
    "PAKR" VARCHAR2(15 CHAR), 
    "AUDTR" VARCHAR2(15 CHAR), 
    "LABEL_PRT_REQD" VARCHAR2(1 CHAR), 
    "CUBE_UOM" VARCHAR2(1 CHAR), 
    "LEN" NUMBER(7,2) DEFAULT 0 NOT NULL ENABLE, 
    "WIDTH" NUMBER(7,2) DEFAULT 0 NOT NULL ENABLE, 
    "HT" NUMBER(7,2) DEFAULT 0 NOT NULL ENABLE, 
    "EVENT_CODE" VARCHAR2(10 CHAR), 
    "ERROR_MODULE" VARCHAR2(10 CHAR), 
    "ERROR_ID" VARCHAR2(40 CHAR), 
    "LAST_FROZN_DATE_TIME" DATE, 
    "MISC_INSTR_CODE_1" VARCHAR2(2 CHAR), 
    "MISC_INSTR_CODE_2" VARCHAR2(2 CHAR), 
    "MISC_INSTR_CODE_3" VARCHAR2(2 CHAR), 
    "MISC_INSTR_CODE_4" VARCHAR2(2 CHAR), 
    "MISC_INSTR_CODE_5" VARCHAR2(2 CHAR), 
    "MISC_NUM_1" NUMBER(9,2) DEFAULT 0 NOT NULL ENABLE, 
    "MISC_NUM_2" NUMBER(9,2) DEFAULT 0 NOT NULL ENABLE, 
    "CREATE_DATE_TIME" DATE, 
    "MOD_DATE_TIME" DATE, 
    "USER_ID" VARCHAR2(15 CHAR), 
    "CARTON_BREAK_ATTR" VARCHAR2(3 CHAR), 
    "LOADER_USER_ID" VARCHAR2(15 CHAR), 
    "LOAD_NBR" VARCHAR2(20 CHAR), 
    "LOAD_DATE_TIME" DATE, 
    "MASTER_BOL" VARCHAR2(20 CHAR), 
    "MASTER_CARTON" VARCHAR2(1 CHAR), 
    "PARCL_SHPMT_NBR" VARCHAR2(20 CHAR), 
    "RTE_RULE_ID" NUMBER(9,0) DEFAULT NULL, 
    "CARTON_GRP_CODE" VARCHAR2(5 CHAR), 
    "CHUTE_ID" VARCHAR2(10 CHAR), 
    "PACK_WAVE_NBR" VARCHAR2(15 CHAR), 
    "CHUTE_ASSIGN_TYPE" VARCHAR2(3 CHAR), 
    "RTE_ID" VARCHAR2(10 CHAR), 
    "QA_FLAG" VARCHAR2(1 CHAR), 
    "BASE_CHRG" NUMBER(9,2) DEFAULT 0 NOT NULL ENABLE, 
    "ADDNL_OPTN_CHRG" NUMBER(9,2) DEFAULT 0 NOT NULL ENABLE, 
    "INSUR_CHRG" NUMBER(9,2) DEFAULT 0 NOT NULL ENABLE, 
    "ACTL_CHRG_AMT" NUMBER(9,2) DEFAULT 0 NOT NULL ENABLE, 
    "PRE_BULK_BASE_CHRG" NUMBER(9,2) DEFAULT 0 NOT NULL ENABLE, 
    "PRE_BULK_ADDNL_OPTN_CHRG" NUMBER(9,2) DEFAULT 0 NOT NULL ENABLE, 
    "MISC_CARTON" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
    "SEL_RULE_ID" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE, 
    "PATH_ID" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE, 
    "INIT_SHIP_VIA" VARCHAR2(4 CHAR), 
    "TMS_TO_ID" VARCHAR2(50 CHAR) DEFAULT NULL, 
    "DIST_CHRG" NUMBER(11,2) DEFAULT 0 NOT NULL ENABLE, 
    "SHIP_DATE_TIME" DATE, 
    "EPC_MATCH_FLAG" VARCHAR2(1 CHAR), 
    "TMS_FLAG" VARCHAR2(1 CHAR), 
    "TMS_STAT_CODE" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE, 
    "LOADED_POSN" VARCHAR2(1 CHAR), 
    "CQ_RULE_ID" NUMBER(9,0), 
    "PLT_MASTER_CARTON_FLAG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
    "CD_MASTER_ID" NUMBER(9,0) NOT NULL ENABLE, 
    "VOCO_INTRNL_REVERSE_ID" VARCHAR2(20 CHAR), 
     CONSTRAINT "PK_CARTON_HDR" PRIMARY KEY ("CARTON_NBR")
  USING INDEX PCTFREE 20 INITRANS 15 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "VBATCH_DEV" ENABLE 
     
   ) PCTFREE 20 PCTUSED 40 INITRANS 10 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
 
  CREATE INDEX "CARTON_HDR_IND_1" ON "CARTON_HDR" ("WHSE", "WAVE_NBR", "WAVE_SEQ_NBR") 
  PCTFREE 20 INITRANS 15 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
 
  CREATE INDEX "CARTON_HDR_IND_10" ON "CARTON_HDR" ("PARCL_SHPMT_NBR") 
  PCTFREE 20 INITRANS 15 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
 
  CREATE INDEX "CARTON_HDR_IND_11" ON "CARTON_HDR" ("SKU_ID") 
  PCTFREE 20 INITRANS 15 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
 
  CREATE INDEX "CARTON_HDR_IND_12" ON "CARTON_HDR" ("PATH_ID") 
  PCTFREE 20 INITRANS 15 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
 
  CREATE INDEX "CARTON_HDR_IND_13" ON "CARTON_HDR" ("VOCO_INTRNL_REVERSE_ID") 
  PCTFREE 20 INITRANS 15 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
 
  CREATE INDEX "CARTON_HDR_IND_14" ON "CARTON_HDR" ("RTE_RULE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
 
  CREATE INDEX "CARTON_HDR_IND_2" ON "CARTON_HDR" ("STAT_CODE", "WHSE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 16777216 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
 
  CREATE INDEX "CARTON_HDR_IND_4" ON "CARTON_HDR" ("PLT_ID") 
  PCTFREE 20 INITRANS 15 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
 
  CREATE INDEX "CARTON_HDR_IND_5" ON "CARTON_HDR" ("SHPMT_NBR") 
  PCTFREE 20 INITRANS 15 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
 
  CREATE INDEX "CARTON_HDR_IND_6" ON "CARTON_HDR" ("BOL") 
  PCTFREE 20 INITRANS 15 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
 
  CREATE INDEX "CARTON_HDR_IND_7" ON "CARTON_HDR" ("LOAD_NBR") 
  PCTFREE 20 INITRANS 15 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
 
  CREATE INDEX "CARTON_HDR_IND_8" ON "CARTON_HDR" ("MASTER_BOL") 
  PCTFREE 20 INITRANS 15 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
 
  CREATE INDEX "CARTON_HDR_IND_9" ON "CARTON_HDR" ("TRKG_NBR") 
  PCTFREE 20 INITRANS 15 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
 
  CREATE INDEX "FK_CARTON_HDR_TO_CD_MASTER" ON "CARTON_HDR" ("CD_MASTER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
 
  CREATE INDEX "FK_CARTON_HDR_TO_LOCN_HDR" ON "CARTON_HDR" ("PICK_LOCN_ID") 
  PCTFREE 20 INITRANS 15 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
 
  CREATE INDEX "FK_CARTON_HDR_TO_LOCN_HDR_CURR" ON "CARTON_HDR" ("CURR_LOCN_ID") 
  PCTFREE 20 INITRANS 15 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
 
  CREATE INDEX "FK_CARTON_HDR_TO_LOCN_HDR_PREV" ON "CARTON_HDR" ("PREV_LOCN_ID") 
  PCTFREE 20 INITRANS 15 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
 
  CREATE INDEX "FK_CARTON_HDR_TO_PKT_HDR" ON "CARTON_HDR" ("PKT_CTRL_NBR") 
  PCTFREE 20 INITRANS 15 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
 
  CREATE INDEX "FK_CARTON_HDR_TO_RULE_HDR" ON "CARTON_HDR" ("CQ_RULE_ID") 
  PCTFREE 20 INITRANS 15 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "VBATCH_DEV" ;
 
  GRANT SELECT ON "CARTON_HDR" TO "VBATCH";
 
  GRANT DELETE ON "CARTON_HDR" TO "VBATCH" WITH GRANT OPTION;
 
  GRANT INSERT ON "CARTON_HDR" TO "VBATCH" WITH GRANT OPTION;
 
  GRANT UPDATE ON "CARTON_HDR" TO "VBATCH" WITH GRANT OPTION;


# --- !Downs

drop table carton_hdr cascade constraints purge;

drop sequence carton_hdr_seq;

