package models;

import java.io.Serializable;
import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;


/**
 * The persistent class for the PKT_HDR database table.
 * VC: Auto-generated by JPA table-to-entity generator July 30.
 * 
 */
@Entity
@Table(name="PKT_HDR")
@NamedQuery(name="PktHdr.findAll", query="SELECT p FROM PktHdr p")
public class PktHdr implements Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name="PKT_CTRL_NBR")
	private String pktCtrlNbr;

	@Column(name="ACCT_RCVBL_ACCT_NBR")
	private String acctRcvblAcctNbr;

	@Column(name="ACCT_RCVBL_CODE")
	private String acctRcvblCode;

	@Column(name="ADDR_CODE")
	private String addrCode;

	@Column(name="ADDR_VALID")
	private String addrValid;

	@Column(name="ADVT_CODE")
	private String advtCode;

	@Temporal(TemporalType.DATE)
	@Column(name="ADVT_DATE")
	private Date advtDate;

	@Temporal(TemporalType.DATE)
	@Column(name="APPT_DATE")
	private Date apptDate;

	@Column(name="APPT_MADE_BY_ID")
	private String apptMadeById;

	@Column(name="APPT_NBR")
	private String apptNbr;

	@Column(name="AUTO_INVC_STAT_CODE")
	private BigDecimal autoInvcStatCode;

	@Column(name="BACK_ORD_FLAG")
	private String backOrdFlag;

	@Column(name="BILL_ACCT_NBR")
	private String billAcctNbr;

	private String bol;

	@Column(name="BOL_BREAK_ATTR")
	private String bolBreakAttr;

	@Column(name="BOL_TYPE")
	private String bolType;

	@Column(name="BUSN_UNIT_CODE")
	private String busnUnitCode;

	@Column(name="CARTON_ASN_REQD")
	private String cartonAsnReqd;

	@Column(name="CARTON_CUBNG_INDIC")
	private BigDecimal cartonCubngIndic;

	@Column(name="CARTON_LABEL_TYPE")
	private String cartonLabelType;

	@Column(name="CD_MASTER_ID")
	private BigDecimal cdMasterId;

	@Column(name="COD_FUNDS")
	private String codFunds;

	@Column(name="COMMODITY_CODE")
	private String commodityCode;

	@Column(name="CONS_ACCT_NBR")
	private String consAcctNbr;

	@Column(name="CONSOL_NBR")
	private String consolNbr;

	@Column(name="CONTNT_LABEL_TYPE")
	private String contntLabelType;

	@Temporal(TemporalType.DATE)
	@Column(name="CREATE_DATE_TIME")
	private Date createDateTime;

	@Column(name="CURR_CODE")
	private String currCode;

	@Column(name="CUST_BROKER_ACCT_NBR")
	private String custBrokerAcctNbr;

	@Column(name="CUST_DEPT")
	private String custDept;

	@Column(name="CUST_PO_NBR")
	private String custPoNbr;

	@Column(name="CUST_RTE")
	private String custRte;

	@Column(name="DC_CTR_NBR")
	private String dcCtrNbr;

	@Column(name="DEPART_AIRPORT")
	private String departAirport;

	@Column(name="DEST_AIRPORT")
	private String destAirport;

	@Column(name="DEST_DOCK_DOOR")
	private String destDockDoor;

	@Temporal(TemporalType.DATE)
	@Column(name="DISC_DATE")
	private Date discDate;

	@Column(name="DOCS_ONLY_SHPMT")
	private String docsOnlyShpmt;

	@Column(name="DSGNATED_MODE_CODE")
	private String dsgnatedModeCode;

	@Column(name="DSGNATED_SERV_LVL")
	private String dsgnatedServLvl;

	@Column(name="DUTY_AND_TAX")
	private BigDecimal dutyAndTax;

	@Column(name="DUTY_TAX_ACCT_NBR")
	private String dutyTaxAcctNbr;

	@Column(name="DUTY_TAX_PAYMENT_TYPE")
	private BigDecimal dutyTaxPaymentType;

	@Column(name="EARLIEST_DLVRY_TIME")
	private String earliestDlvryTime;

	@Column(name="EST_CARTON")
	private BigDecimal estCarton;

	@Column(name="EST_CARTON_BRIDGED")
	private BigDecimal estCartonBridged;

	@Column(name="EST_CARTON_PER_PALLET_BRIDGED")
	private BigDecimal estCartonPerPalletBridged;

	@Column(name="EST_PALLET")
	private BigDecimal estPallet;

	@Column(name="EST_PALLET_BRIDGED")
	private BigDecimal estPalletBridged;

	@Column(name="EST_VOL")
	private BigDecimal estVol;

	@Column(name="EST_VOL_BRIDGED")
	private BigDecimal estVolBridged;

	@Column(name="EST_WT")
	private BigDecimal estWt;

	@Column(name="EST_WT_BRIDGED")
	private BigDecimal estWtBridged;

	@Column(name="FIRST_ZONE")
	private String firstZone;

	@Column(name="FREIGHT_TERMS")
	private String freightTerms;

	@Column(name="FRT_CLASS")
	private String frtClass;

	@Column(name="FRT_FORWARDER_ACCT_NBR")
	private String frtForwarderAcctNbr;

	@Column(name="FTSR_NBR")
	private String ftsrNbr;

	@Column(name="GLOBAL_LOCN_NBR")
	private String globalLocnNbr;

	@Column(name="HUB_ID")
	private BigDecimal hubId;

	@Column(name="IMPORTER_DEFN")
	private String importerDefn;

	@Column(name="INCO_TERMS")
	private String incoTerms;

	@Column(name="INCOTERM_ID")
	private String incotermId;

	@Column(name="INIT_SHIP_VIA")
	private String initShipVia;

	@Column(name="INTL_GOODS_DESC")
	private String intlGoodsDesc;

	@Column(name="INVN_SHRTG_FLAG")
	private String invnShrtgFlag;

	@Column(name="IS_CUST_PICKUP_FLAG")
	private String isCustPickupFlag;

	@Column(name="IS_DIRECT_ALLOW_FLAG")
	private String isDirectAllowFlag;

	@Column(name="IS_HAZMAT_FLAG")
	private String isHazmatFlag;

	@Column(name="IS_PARTL_PLAN_FLAG")
	private String isPartlPlanFlag;

	@Column(name="IS_PERISH_FLAG")
	private String isPerishFlag;

	@Column(name="LANG_ID")
	private String langId;

	@Column(name="LAST_ZONE")
	private String lastZone;

	@Column(name="MAJOR_PKT_GRP_ATTR")
	private String majorPktGrpAttr;

	@Column(name="MANG_TERR")
	private String mangTerr;

	@Column(name="MANIF_NBR")
	private String manifNbr;

	@Column(name="MANIF_TYPE")
	private String manifType;

	@Column(name="MARK_FOR")
	private String markFor;

	@Column(name="MAX_CARTON_UNITS")
	private BigDecimal maxCartonUnits;

	@Column(name="MAX_CARTON_WT")
	private BigDecimal maxCartonWt;

	@Column(name="MERCH_CLASS")
	private String merchClass;

	@Column(name="MERCH_CODE")
	private String merchCode;

	@Column(name="MERCH_DIV")
	private String merchDiv;

	@Temporal(TemporalType.DATE)
	@Column(name="MOD_DATE_TIME")
	private Date modDateTime;

	@Column(name="MONETARY_VALUE")
	private BigDecimal monetaryValue;

	@Column(name="MV_CURRENCY_CODE")
	private String mvCurrencyCode;

	@Column(name="NBR_OF_CONTNT_LABEL")
	private BigDecimal nbrOfContntLabel;

	@Column(name="NBR_OF_HNGR")
	private BigDecimal nbrOfHngr;

	@Column(name="NBR_OF_LABEL")
	private BigDecimal nbrOfLabel;

	@Column(name="NBR_OF_PAKNG_SLIPS")
	private BigDecimal nbrOfPakngSlips;

	@Column(name="NBR_OF_TIMES_APPT_CHGD")
	private BigDecimal nbrOfTimesApptChgd;

	@Column(name="NBR_OF_ZONES")
	private BigDecimal nbrOfZones;

	@Column(name="NBR_ORDS_FOR_SWC")
	private BigDecimal nbrOrdsForSwc;

	@Temporal(TemporalType.DATE)
	@Column(name="ORD_DATE")
	private Date ordDate;

	@Column(name="ORD_NBR")
	private String ordNbr;

	@Column(name="ORD_NBR_FOR_SWC")
	private BigDecimal ordNbrForSwc;

	@Column(name="ORD_SFX")
	private String ordSfx;

	@Column(name="ORD_TYPE")
	private String ordType;

	@Column(name="ORGN_DOCK")
	private String orgnDock;

	@Column(name="ORIG_SHIP_VIA")
	private String origShipVia;

	@Column(name="PACK_SLIP_PRT_CNT")
	private BigDecimal packSlipPrtCnt;

	@Column(name="PACK_SLIP_TYPE")
	private String packSlipType;

	@Column(name="PARENT_ORD_ID")
	private BigDecimal parentOrdId;

	@Column(name="PARTIES_RELATED")
	private String partiesRelated;

	@Column(name="PARTL_CARTON_MIN_WT")
	private BigDecimal partlCartonMinWt;

	@Column(name="PARTL_CARTON_OPTN")
	private String partlCartonOptn;

	@Column(name="PATH_ID")
	private BigDecimal pathId;

	@Column(name="PKT_CONSOL_PROF")
	private String pktConsolProf;

	@Temporal(TemporalType.DATE)
	@Column(name="PKT_GENRTN_DATE_TIME")
	private Date pktGenrtnDateTime;

	@Column(name="PKT_NBR")
	private String pktNbr;

	@Column(name="PKT_SFX")
	private String pktSfx;

	@Column(name="PKT_TYPE")
	private String pktType;

	@Column(name="PLAN_BOL")
	private String planBol;

	@Column(name="PLAN_ID")
	private String planId;

	@Column(name="PLAN_LOAD_NBR")
	private String planLoadNbr;

	@Column(name="PLAN_MASTER_BOL")
	private String planMasterBol;

	@Column(name="PLAN_SHPMT_NBR")
	private String planShpmtNbr;

	@Column(name="PLANNING_DEST")
	private String planningDest;

	@Column(name="PLANNING_ORGN")
	private String planningOrgn;

	@Column(name="PLT_CONTNT_LABEL_TYPE")
	private String pltContntLabelType;

	@Column(name="PLT_CUBNG_INDIC")
	private BigDecimal pltCubngIndic;

	@Column(name="PLTZ_ORD")
	private String pltzOrd;

	@Column(name="PNH_CTRL_NBR")
	private String pnhCtrlNbr;

	@Column(name="PNH_FLAG")
	private String pnhFlag;

	@Column(name="PO_TYPE")
	private String poType;

	@Column(name="PORT_OF_DISCHARGE")
	private String portOfDischarge;

	@Column(name="PORT_OF_LOADING")
	private String portOfLoading;

	@Column(name="PRE_PACK_FLAG")
	private BigDecimal prePackFlag;

	@Column(name="PRE_STIKR_CODE")
	private String preStikrCode;

	@Column(name="PRIMARY_MAXI_ADDR_NBR")
	private String primaryMaxiAddrNbr;

	@Column(name="PRINT_CANADIAN_CUST_INVC_FLAG")
	private String printCanadianCustInvcFlag;

	@Column(name="PRINT_COO")
	private String printCoo;

	@Column(name="PRINT_DOCK_RCPT_FLAG")
	private String printDockRcptFlag;

	@Column(name="PRINT_INV")
	private String printInv;

	@Column(name="PRINT_NAFTA_COO_FLAG")
	private String printNaftaCooFlag;

	@Column(name="PRINT_OCEAN_BOL_FLAG")
	private String printOceanBolFlag;

	@Column(name="PRINT_PKG_LIST_FLAG")
	private String printPkgListFlag;

	@Column(name="PRINT_SED")
	private String printSed;

	@Column(name="PRINT_SHPR_LTR_OF_INSTR_FLAG")
	private String printShprLtrOfInstrFlag;

	@Column(name="PRO_NBR")
	private String proNbr;

	@Column(name="PROC_RTL_RTE_RULE")
	private String procRtlRteRule;

	@Column(name="PROD_SCHED_REF_NBR")
	private String prodSchedRefNbr;

	@Column(name="PROD_VALUE")
	private BigDecimal prodValue;

	@Column(name="PRTY_CODE")
	private String prtyCode;

	@Column(name="PRTY_SFX")
	private String prtySfx;

	@Column(name="PRTY_TYPE")
	private String prtyType;

	@Column(name="REPL_FLAG")
	private String replFlag;

	@Column(name="RTE_ATTR")
	private String rteAttr;

	@Column(name="RTE_GUIDE_NBR")
	private String rteGuideNbr;

	@Column(name="RTE_ID")
	private String rteId;

	@Column(name="RTE_LOAD_SEQ")
	private BigDecimal rteLoadSeq;

	@Column(name="RTE_STOP_SEQ")
	private BigDecimal rteStopSeq;

	@Column(name="RTE_TO")
	private String rteTo;

	@Column(name="RTE_TYPE_1")
	private String rteType1;

	@Column(name="RTE_TYPE_2")
	private String rteType2;

	@Column(name="RTE_ZIP")
	private String rteZip;

	@Column(name="SALE_GRP")
	private String saleGrp;

	@Temporal(TemporalType.DATE)
	@Column(name="SCHED_DLVRY_DATE")
	private Date schedDlvryDate;

	@Temporal(TemporalType.DATE)
	@Column(name="SCHED_DLVRY_DATE_END")
	private Date schedDlvryDateEnd;

	@Column(name="SECONDARY_MAXI_ADDR_NBR")
	private String secondaryMaxiAddrNbr;

	@Column(name="SEL_RULE_PRTY")
	private BigDecimal selRulePrty;

	@Column(name="SHIP_VIA")
	private String shipVia;

	@Column(name="SHIP_W_CTRL_NBR")
	private String shipWCtrlNbr;

	private String shipto;

	@Column(name="SHIPTO_ADDR_1")
	private String shiptoAddr1;

	@Column(name="SHIPTO_ADDR_2")
	private String shiptoAddr2;

	@Column(name="SHIPTO_ADDR_3")
	private String shiptoAddr3;

	@Column(name="SHIPTO_CITY")
	private String shiptoCity;

	@Column(name="SHIPTO_CNTRY")
	private String shiptoCntry;

	@Column(name="SHIPTO_CNTY")
	private String shiptoCnty;

	@Column(name="SHIPTO_CONTACT")
	private String shiptoContact;

	@Column(name="SHIPTO_NAME")
	private String shiptoName;

	@Column(name="SHIPTO_STATE")
	private String shiptoState;

	@Column(name="SHIPTO_WHSE")
	private String shiptoWhse;

	@Column(name="SHIPTO_ZIP")
	private String shiptoZip;

	@Column(name="SHPMT_NBR")
	private String shpmtNbr;

	@Column(name="SHPR_ID")
	private String shprId;

	@Column(name="SHPR_ORD_ID")
	private String shprOrdId;

	@Column(name="SKU_INVN_VERF")
	private String skuInvnVerf;

	@Column(name="SLSPRSN_NBR")
	private String slsprsnNbr;

	@Column(name="SNGL_UNIT_FLAG")
	private String snglUnitFlag;

	private String soldto;

	@Column(name="SOLDTO_ADDR_1")
	private String soldtoAddr1;

	@Column(name="SOLDTO_ADDR_2")
	private String soldtoAddr2;

	@Column(name="SOLDTO_ADDR_3")
	private String soldtoAddr3;

	@Column(name="SOLDTO_CITY")
	private String soldtoCity;

	@Column(name="SOLDTO_CNTRY")
	private String soldtoCntry;

	@Column(name="SOLDTO_NAME")
	private String soldtoName;

	@Column(name="SOLDTO_STATE")
	private String soldtoState;

	@Column(name="SOLDTO_ZIP")
	private String soldtoZip;

	@Column(name="SPL_INSTR_CODE_1")
	private String splInstrCode1;

	@Column(name="SPL_INSTR_CODE_10")
	private String splInstrCode10;

	@Column(name="SPL_INSTR_CODE_2")
	private String splInstrCode2;

	@Column(name="SPL_INSTR_CODE_3")
	private String splInstrCode3;

	@Column(name="SPL_INSTR_CODE_4")
	private String splInstrCode4;

	@Column(name="SPL_INSTR_CODE_5")
	private String splInstrCode5;

	@Column(name="SPL_INSTR_CODE_6")
	private String splInstrCode6;

	@Column(name="SPL_INSTR_CODE_7")
	private String splInstrCode7;

	@Column(name="SPL_INSTR_CODE_8")
	private String splInstrCode8;

	@Column(name="SPL_INSTR_CODE_9")
	private String splInstrCode9;

	@Column(name="SRL_NBR_TRK_FLAG")
	private BigDecimal srlNbrTrkFlag;

	@Temporal(TemporalType.DATE)
	@Column(name="START_SHIP_DATE")
	private Date startShipDate;

	@Temporal(TemporalType.DATE)
	@Column(name="STOP_SHIP_DATE")
	private Date stopShipDate;

	@Column(name="STOP_SHIP_RULE")
	private String stopShipRule;

	@Column(name="STORE_NBR")
	private String storeNbr;

	@Column(name="STORE_TYPE")
	private String storeType;

	@Column(name="SWC_NBR_SEQ")
	private BigDecimal swcNbrSeq;

	@Column(name="TEL_NBR")
	private String telNbr;

	@Column(name="TEMP_ZONE")
	private String tempZone;

	@Column(name="TERMS_CODE")
	private String termsCode;

	@Column(name="TERMS_DESC")
	private String termsDesc;

	@Column(name="TERMS_PCNT")
	private BigDecimal termsPcnt;

	@Column(name="TERR_CODE")
	private String terrCode;

	@Column(name="THRD_PARTY_BILL")
	private String thrdPartyBill;

	@Column(name="TMS_ORD_TYPE")
	private String tmsOrdType;

	@Column(name="TMS_PO_FLAG")
	private String tmsPoFlag;

	@Column(name="TMS_PROC")
	private String tmsProc;

	@Column(name="TOTAL_DLRS_DISC")
	private BigDecimal totalDlrsDisc;

	@Column(name="TOTAL_DLRS_UNDISC")
	private BigDecimal totalDlrsUndisc;

	@Column(name="TRANSPRT_RESP_CODE")
	private String transprtRespCode;

	@Column(name="TRLR_SIZE")
	private String trlrSize;

	@Column(name="TRLR_STOP_SEQ_NBR")
	private BigDecimal trlrStopSeqNbr;

	@Column(name="TRLR_TYPE")
	private String trlrType;

	@Column(name="UN_NBR")
	private String unNbr;

	@Column(name="USER_ID")
	private String userId;

	@Column(name="VENDOR_NBR")
	private String vendorNbr;

	@Column(name="WAVE_LABEL_TYPE")
	private String waveLabelType;

	private String whse;

	@Column(name="WHSE_XFER_FLAG")
	private String whseXferFlag;

	@Column(name="XFER_WHSE")
	private String xferWhse;

	@Column(name="ZONE_SKIP")
	private String zoneSkip;

	//bi-directional one-to-one association to PktHdrIntrnl
	@OneToOne
	@JoinColumn(name="PKT_CTRL_NBR")
	private PktHdrIntrnl pktHdrIntrnl;

	public PktHdr() {
	}

	public String getPktCtrlNbr() {
		return this.pktCtrlNbr;
	}

	public void setPktCtrlNbr(String pktCtrlNbr) {
		this.pktCtrlNbr = pktCtrlNbr;
	}

	public String getAcctRcvblAcctNbr() {
		return this.acctRcvblAcctNbr;
	}

	public void setAcctRcvblAcctNbr(String acctRcvblAcctNbr) {
		this.acctRcvblAcctNbr = acctRcvblAcctNbr;
	}

	public String getAcctRcvblCode() {
		return this.acctRcvblCode;
	}

	public void setAcctRcvblCode(String acctRcvblCode) {
		this.acctRcvblCode = acctRcvblCode;
	}

	public String getAddrCode() {
		return this.addrCode;
	}

	public void setAddrCode(String addrCode) {
		this.addrCode = addrCode;
	}

	public String getAddrValid() {
		return this.addrValid;
	}

	public void setAddrValid(String addrValid) {
		this.addrValid = addrValid;
	}

	public String getAdvtCode() {
		return this.advtCode;
	}

	public void setAdvtCode(String advtCode) {
		this.advtCode = advtCode;
	}

	public Date getAdvtDate() {
		return this.advtDate;
	}

	public void setAdvtDate(Date advtDate) {
		this.advtDate = advtDate;
	}

	public Date getApptDate() {
		return this.apptDate;
	}

	public void setApptDate(Date apptDate) {
		this.apptDate = apptDate;
	}

	public String getApptMadeById() {
		return this.apptMadeById;
	}

	public void setApptMadeById(String apptMadeById) {
		this.apptMadeById = apptMadeById;
	}

	public String getApptNbr() {
		return this.apptNbr;
	}

	public void setApptNbr(String apptNbr) {
		this.apptNbr = apptNbr;
	}

	public BigDecimal getAutoInvcStatCode() {
		return this.autoInvcStatCode;
	}

	public void setAutoInvcStatCode(BigDecimal autoInvcStatCode) {
		this.autoInvcStatCode = autoInvcStatCode;
	}

	public String getBackOrdFlag() {
		return this.backOrdFlag;
	}

	public void setBackOrdFlag(String backOrdFlag) {
		this.backOrdFlag = backOrdFlag;
	}

	public String getBillAcctNbr() {
		return this.billAcctNbr;
	}

	public void setBillAcctNbr(String billAcctNbr) {
		this.billAcctNbr = billAcctNbr;
	}

	public String getBol() {
		return this.bol;
	}

	public void setBol(String bol) {
		this.bol = bol;
	}

	public String getBolBreakAttr() {
		return this.bolBreakAttr;
	}

	public void setBolBreakAttr(String bolBreakAttr) {
		this.bolBreakAttr = bolBreakAttr;
	}

	public String getBolType() {
		return this.bolType;
	}

	public void setBolType(String bolType) {
		this.bolType = bolType;
	}

	public String getBusnUnitCode() {
		return this.busnUnitCode;
	}

	public void setBusnUnitCode(String busnUnitCode) {
		this.busnUnitCode = busnUnitCode;
	}

	public String getCartonAsnReqd() {
		return this.cartonAsnReqd;
	}

	public void setCartonAsnReqd(String cartonAsnReqd) {
		this.cartonAsnReqd = cartonAsnReqd;
	}

	public BigDecimal getCartonCubngIndic() {
		return this.cartonCubngIndic;
	}

	public void setCartonCubngIndic(BigDecimal cartonCubngIndic) {
		this.cartonCubngIndic = cartonCubngIndic;
	}

	public String getCartonLabelType() {
		return this.cartonLabelType;
	}

	public void setCartonLabelType(String cartonLabelType) {
		this.cartonLabelType = cartonLabelType;
	}

	public BigDecimal getCdMasterId() {
		return this.cdMasterId;
	}

	public void setCdMasterId(BigDecimal cdMasterId) {
		this.cdMasterId = cdMasterId;
	}

	public String getCodFunds() {
		return this.codFunds;
	}

	public void setCodFunds(String codFunds) {
		this.codFunds = codFunds;
	}

	public String getCommodityCode() {
		return this.commodityCode;
	}

	public void setCommodityCode(String commodityCode) {
		this.commodityCode = commodityCode;
	}

	public String getConsAcctNbr() {
		return this.consAcctNbr;
	}

	public void setConsAcctNbr(String consAcctNbr) {
		this.consAcctNbr = consAcctNbr;
	}

	public String getConsolNbr() {
		return this.consolNbr;
	}

	public void setConsolNbr(String consolNbr) {
		this.consolNbr = consolNbr;
	}

	public String getContntLabelType() {
		return this.contntLabelType;
	}

	public void setContntLabelType(String contntLabelType) {
		this.contntLabelType = contntLabelType;
	}

	public Date getCreateDateTime() {
		return this.createDateTime;
	}

	public void setCreateDateTime(Date createDateTime) {
		this.createDateTime = createDateTime;
	}

	public String getCurrCode() {
		return this.currCode;
	}

	public void setCurrCode(String currCode) {
		this.currCode = currCode;
	}

	public String getCustBrokerAcctNbr() {
		return this.custBrokerAcctNbr;
	}

	public void setCustBrokerAcctNbr(String custBrokerAcctNbr) {
		this.custBrokerAcctNbr = custBrokerAcctNbr;
	}

	public String getCustDept() {
		return this.custDept;
	}

	public void setCustDept(String custDept) {
		this.custDept = custDept;
	}

	public String getCustPoNbr() {
		return this.custPoNbr;
	}

	public void setCustPoNbr(String custPoNbr) {
		this.custPoNbr = custPoNbr;
	}

	public String getCustRte() {
		return this.custRte;
	}

	public void setCustRte(String custRte) {
		this.custRte = custRte;
	}

	public String getDcCtrNbr() {
		return this.dcCtrNbr;
	}

	public void setDcCtrNbr(String dcCtrNbr) {
		this.dcCtrNbr = dcCtrNbr;
	}

	public String getDepartAirport() {
		return this.departAirport;
	}

	public void setDepartAirport(String departAirport) {
		this.departAirport = departAirport;
	}

	public String getDestAirport() {
		return this.destAirport;
	}

	public void setDestAirport(String destAirport) {
		this.destAirport = destAirport;
	}

	public String getDestDockDoor() {
		return this.destDockDoor;
	}

	public void setDestDockDoor(String destDockDoor) {
		this.destDockDoor = destDockDoor;
	}

	public Date getDiscDate() {
		return this.discDate;
	}

	public void setDiscDate(Date discDate) {
		this.discDate = discDate;
	}

	public String getDocsOnlyShpmt() {
		return this.docsOnlyShpmt;
	}

	public void setDocsOnlyShpmt(String docsOnlyShpmt) {
		this.docsOnlyShpmt = docsOnlyShpmt;
	}

	public String getDsgnatedModeCode() {
		return this.dsgnatedModeCode;
	}

	public void setDsgnatedModeCode(String dsgnatedModeCode) {
		this.dsgnatedModeCode = dsgnatedModeCode;
	}

	public String getDsgnatedServLvl() {
		return this.dsgnatedServLvl;
	}

	public void setDsgnatedServLvl(String dsgnatedServLvl) {
		this.dsgnatedServLvl = dsgnatedServLvl;
	}

	public BigDecimal getDutyAndTax() {
		return this.dutyAndTax;
	}

	public void setDutyAndTax(BigDecimal dutyAndTax) {
		this.dutyAndTax = dutyAndTax;
	}

	public String getDutyTaxAcctNbr() {
		return this.dutyTaxAcctNbr;
	}

	public void setDutyTaxAcctNbr(String dutyTaxAcctNbr) {
		this.dutyTaxAcctNbr = dutyTaxAcctNbr;
	}

	public BigDecimal getDutyTaxPaymentType() {
		return this.dutyTaxPaymentType;
	}

	public void setDutyTaxPaymentType(BigDecimal dutyTaxPaymentType) {
		this.dutyTaxPaymentType = dutyTaxPaymentType;
	}

	public String getEarliestDlvryTime() {
		return this.earliestDlvryTime;
	}

	public void setEarliestDlvryTime(String earliestDlvryTime) {
		this.earliestDlvryTime = earliestDlvryTime;
	}

	public BigDecimal getEstCarton() {
		return this.estCarton;
	}

	public void setEstCarton(BigDecimal estCarton) {
		this.estCarton = estCarton;
	}

	public BigDecimal getEstCartonBridged() {
		return this.estCartonBridged;
	}

	public void setEstCartonBridged(BigDecimal estCartonBridged) {
		this.estCartonBridged = estCartonBridged;
	}

	public BigDecimal getEstCartonPerPalletBridged() {
		return this.estCartonPerPalletBridged;
	}

	public void setEstCartonPerPalletBridged(BigDecimal estCartonPerPalletBridged) {
		this.estCartonPerPalletBridged = estCartonPerPalletBridged;
	}

	public BigDecimal getEstPallet() {
		return this.estPallet;
	}

	public void setEstPallet(BigDecimal estPallet) {
		this.estPallet = estPallet;
	}

	public BigDecimal getEstPalletBridged() {
		return this.estPalletBridged;
	}

	public void setEstPalletBridged(BigDecimal estPalletBridged) {
		this.estPalletBridged = estPalletBridged;
	}

	public BigDecimal getEstVol() {
		return this.estVol;
	}

	public void setEstVol(BigDecimal estVol) {
		this.estVol = estVol;
	}

	public BigDecimal getEstVolBridged() {
		return this.estVolBridged;
	}

	public void setEstVolBridged(BigDecimal estVolBridged) {
		this.estVolBridged = estVolBridged;
	}

	public BigDecimal getEstWt() {
		return this.estWt;
	}

	public void setEstWt(BigDecimal estWt) {
		this.estWt = estWt;
	}

	public BigDecimal getEstWtBridged() {
		return this.estWtBridged;
	}

	public void setEstWtBridged(BigDecimal estWtBridged) {
		this.estWtBridged = estWtBridged;
	}

	public String getFirstZone() {
		return this.firstZone;
	}

	public void setFirstZone(String firstZone) {
		this.firstZone = firstZone;
	}

	public String getFreightTerms() {
		return this.freightTerms;
	}

	public void setFreightTerms(String freightTerms) {
		this.freightTerms = freightTerms;
	}

	public String getFrtClass() {
		return this.frtClass;
	}

	public void setFrtClass(String frtClass) {
		this.frtClass = frtClass;
	}

	public String getFrtForwarderAcctNbr() {
		return this.frtForwarderAcctNbr;
	}

	public void setFrtForwarderAcctNbr(String frtForwarderAcctNbr) {
		this.frtForwarderAcctNbr = frtForwarderAcctNbr;
	}

	public String getFtsrNbr() {
		return this.ftsrNbr;
	}

	public void setFtsrNbr(String ftsrNbr) {
		this.ftsrNbr = ftsrNbr;
	}

	public String getGlobalLocnNbr() {
		return this.globalLocnNbr;
	}

	public void setGlobalLocnNbr(String globalLocnNbr) {
		this.globalLocnNbr = globalLocnNbr;
	}

	public BigDecimal getHubId() {
		return this.hubId;
	}

	public void setHubId(BigDecimal hubId) {
		this.hubId = hubId;
	}

	public String getImporterDefn() {
		return this.importerDefn;
	}

	public void setImporterDefn(String importerDefn) {
		this.importerDefn = importerDefn;
	}

	public String getIncoTerms() {
		return this.incoTerms;
	}

	public void setIncoTerms(String incoTerms) {
		this.incoTerms = incoTerms;
	}

	public String getIncotermId() {
		return this.incotermId;
	}

	public void setIncotermId(String incotermId) {
		this.incotermId = incotermId;
	}

	public String getInitShipVia() {
		return this.initShipVia;
	}

	public void setInitShipVia(String initShipVia) {
		this.initShipVia = initShipVia;
	}

	public String getIntlGoodsDesc() {
		return this.intlGoodsDesc;
	}

	public void setIntlGoodsDesc(String intlGoodsDesc) {
		this.intlGoodsDesc = intlGoodsDesc;
	}

	public String getInvnShrtgFlag() {
		return this.invnShrtgFlag;
	}

	public void setInvnShrtgFlag(String invnShrtgFlag) {
		this.invnShrtgFlag = invnShrtgFlag;
	}

	public String getIsCustPickupFlag() {
		return this.isCustPickupFlag;
	}

	public void setIsCustPickupFlag(String isCustPickupFlag) {
		this.isCustPickupFlag = isCustPickupFlag;
	}

	public String getIsDirectAllowFlag() {
		return this.isDirectAllowFlag;
	}

	public void setIsDirectAllowFlag(String isDirectAllowFlag) {
		this.isDirectAllowFlag = isDirectAllowFlag;
	}

	public String getIsHazmatFlag() {
		return this.isHazmatFlag;
	}

	public void setIsHazmatFlag(String isHazmatFlag) {
		this.isHazmatFlag = isHazmatFlag;
	}

	public String getIsPartlPlanFlag() {
		return this.isPartlPlanFlag;
	}

	public void setIsPartlPlanFlag(String isPartlPlanFlag) {
		this.isPartlPlanFlag = isPartlPlanFlag;
	}

	public String getIsPerishFlag() {
		return this.isPerishFlag;
	}

	public void setIsPerishFlag(String isPerishFlag) {
		this.isPerishFlag = isPerishFlag;
	}

	public String getLangId() {
		return this.langId;
	}

	public void setLangId(String langId) {
		this.langId = langId;
	}

	public String getLastZone() {
		return this.lastZone;
	}

	public void setLastZone(String lastZone) {
		this.lastZone = lastZone;
	}

	public String getMajorPktGrpAttr() {
		return this.majorPktGrpAttr;
	}

	public void setMajorPktGrpAttr(String majorPktGrpAttr) {
		this.majorPktGrpAttr = majorPktGrpAttr;
	}

	public String getMangTerr() {
		return this.mangTerr;
	}

	public void setMangTerr(String mangTerr) {
		this.mangTerr = mangTerr;
	}

	public String getManifNbr() {
		return this.manifNbr;
	}

	public void setManifNbr(String manifNbr) {
		this.manifNbr = manifNbr;
	}

	public String getManifType() {
		return this.manifType;
	}

	public void setManifType(String manifType) {
		this.manifType = manifType;
	}

	public String getMarkFor() {
		return this.markFor;
	}

	public void setMarkFor(String markFor) {
		this.markFor = markFor;
	}

	public BigDecimal getMaxCartonUnits() {
		return this.maxCartonUnits;
	}

	public void setMaxCartonUnits(BigDecimal maxCartonUnits) {
		this.maxCartonUnits = maxCartonUnits;
	}

	public BigDecimal getMaxCartonWt() {
		return this.maxCartonWt;
	}

	public void setMaxCartonWt(BigDecimal maxCartonWt) {
		this.maxCartonWt = maxCartonWt;
	}

	public String getMerchClass() {
		return this.merchClass;
	}

	public void setMerchClass(String merchClass) {
		this.merchClass = merchClass;
	}

	public String getMerchCode() {
		return this.merchCode;
	}

	public void setMerchCode(String merchCode) {
		this.merchCode = merchCode;
	}

	public String getMerchDiv() {
		return this.merchDiv;
	}

	public void setMerchDiv(String merchDiv) {
		this.merchDiv = merchDiv;
	}

	public Date getModDateTime() {
		return this.modDateTime;
	}

	public void setModDateTime(Date modDateTime) {
		this.modDateTime = modDateTime;
	}

	public BigDecimal getMonetaryValue() {
		return this.monetaryValue;
	}

	public void setMonetaryValue(BigDecimal monetaryValue) {
		this.monetaryValue = monetaryValue;
	}

	public String getMvCurrencyCode() {
		return this.mvCurrencyCode;
	}

	public void setMvCurrencyCode(String mvCurrencyCode) {
		this.mvCurrencyCode = mvCurrencyCode;
	}

	public BigDecimal getNbrOfContntLabel() {
		return this.nbrOfContntLabel;
	}

	public void setNbrOfContntLabel(BigDecimal nbrOfContntLabel) {
		this.nbrOfContntLabel = nbrOfContntLabel;
	}

	public BigDecimal getNbrOfHngr() {
		return this.nbrOfHngr;
	}

	public void setNbrOfHngr(BigDecimal nbrOfHngr) {
		this.nbrOfHngr = nbrOfHngr;
	}

	public BigDecimal getNbrOfLabel() {
		return this.nbrOfLabel;
	}

	public void setNbrOfLabel(BigDecimal nbrOfLabel) {
		this.nbrOfLabel = nbrOfLabel;
	}

	public BigDecimal getNbrOfPakngSlips() {
		return this.nbrOfPakngSlips;
	}

	public void setNbrOfPakngSlips(BigDecimal nbrOfPakngSlips) {
		this.nbrOfPakngSlips = nbrOfPakngSlips;
	}

	public BigDecimal getNbrOfTimesApptChgd() {
		return this.nbrOfTimesApptChgd;
	}

	public void setNbrOfTimesApptChgd(BigDecimal nbrOfTimesApptChgd) {
		this.nbrOfTimesApptChgd = nbrOfTimesApptChgd;
	}

	public BigDecimal getNbrOfZones() {
		return this.nbrOfZones;
	}

	public void setNbrOfZones(BigDecimal nbrOfZones) {
		this.nbrOfZones = nbrOfZones;
	}

	public BigDecimal getNbrOrdsForSwc() {
		return this.nbrOrdsForSwc;
	}

	public void setNbrOrdsForSwc(BigDecimal nbrOrdsForSwc) {
		this.nbrOrdsForSwc = nbrOrdsForSwc;
	}

	public Date getOrdDate() {
		return this.ordDate;
	}

	public void setOrdDate(Date ordDate) {
		this.ordDate = ordDate;
	}

	public String getOrdNbr() {
		return this.ordNbr;
	}

	public void setOrdNbr(String ordNbr) {
		this.ordNbr = ordNbr;
	}

	public BigDecimal getOrdNbrForSwc() {
		return this.ordNbrForSwc;
	}

	public void setOrdNbrForSwc(BigDecimal ordNbrForSwc) {
		this.ordNbrForSwc = ordNbrForSwc;
	}

	public String getOrdSfx() {
		return this.ordSfx;
	}

	public void setOrdSfx(String ordSfx) {
		this.ordSfx = ordSfx;
	}

	public String getOrdType() {
		return this.ordType;
	}

	public void setOrdType(String ordType) {
		this.ordType = ordType;
	}

	public String getOrgnDock() {
		return this.orgnDock;
	}

	public void setOrgnDock(String orgnDock) {
		this.orgnDock = orgnDock;
	}

	public String getOrigShipVia() {
		return this.origShipVia;
	}

	public void setOrigShipVia(String origShipVia) {
		this.origShipVia = origShipVia;
	}

	public BigDecimal getPackSlipPrtCnt() {
		return this.packSlipPrtCnt;
	}

	public void setPackSlipPrtCnt(BigDecimal packSlipPrtCnt) {
		this.packSlipPrtCnt = packSlipPrtCnt;
	}

	public String getPackSlipType() {
		return this.packSlipType;
	}

	public void setPackSlipType(String packSlipType) {
		this.packSlipType = packSlipType;
	}

	public BigDecimal getParentOrdId() {
		return this.parentOrdId;
	}

	public void setParentOrdId(BigDecimal parentOrdId) {
		this.parentOrdId = parentOrdId;
	}

	public String getPartiesRelated() {
		return this.partiesRelated;
	}

	public void setPartiesRelated(String partiesRelated) {
		this.partiesRelated = partiesRelated;
	}

	public BigDecimal getPartlCartonMinWt() {
		return this.partlCartonMinWt;
	}

	public void setPartlCartonMinWt(BigDecimal partlCartonMinWt) {
		this.partlCartonMinWt = partlCartonMinWt;
	}

	public String getPartlCartonOptn() {
		return this.partlCartonOptn;
	}

	public void setPartlCartonOptn(String partlCartonOptn) {
		this.partlCartonOptn = partlCartonOptn;
	}

	public BigDecimal getPathId() {
		return this.pathId;
	}

	public void setPathId(BigDecimal pathId) {
		this.pathId = pathId;
	}

	public String getPktConsolProf() {
		return this.pktConsolProf;
	}

	public void setPktConsolProf(String pktConsolProf) {
		this.pktConsolProf = pktConsolProf;
	}

	public Date getPktGenrtnDateTime() {
		return this.pktGenrtnDateTime;
	}

	public void setPktGenrtnDateTime(Date pktGenrtnDateTime) {
		this.pktGenrtnDateTime = pktGenrtnDateTime;
	}

	public String getPktNbr() {
		return this.pktNbr;
	}

	public void setPktNbr(String pktNbr) {
		this.pktNbr = pktNbr;
	}

	public String getPktSfx() {
		return this.pktSfx;
	}

	public void setPktSfx(String pktSfx) {
		this.pktSfx = pktSfx;
	}

	public String getPktType() {
		return this.pktType;
	}

	public void setPktType(String pktType) {
		this.pktType = pktType;
	}

	public String getPlanBol() {
		return this.planBol;
	}

	public void setPlanBol(String planBol) {
		this.planBol = planBol;
	}

	public String getPlanId() {
		return this.planId;
	}

	public void setPlanId(String planId) {
		this.planId = planId;
	}

	public String getPlanLoadNbr() {
		return this.planLoadNbr;
	}

	public void setPlanLoadNbr(String planLoadNbr) {
		this.planLoadNbr = planLoadNbr;
	}

	public String getPlanMasterBol() {
		return this.planMasterBol;
	}

	public void setPlanMasterBol(String planMasterBol) {
		this.planMasterBol = planMasterBol;
	}

	public String getPlanShpmtNbr() {
		return this.planShpmtNbr;
	}

	public void setPlanShpmtNbr(String planShpmtNbr) {
		this.planShpmtNbr = planShpmtNbr;
	}

	public String getPlanningDest() {
		return this.planningDest;
	}

	public void setPlanningDest(String planningDest) {
		this.planningDest = planningDest;
	}

	public String getPlanningOrgn() {
		return this.planningOrgn;
	}

	public void setPlanningOrgn(String planningOrgn) {
		this.planningOrgn = planningOrgn;
	}

	public String getPltContntLabelType() {
		return this.pltContntLabelType;
	}

	public void setPltContntLabelType(String pltContntLabelType) {
		this.pltContntLabelType = pltContntLabelType;
	}

	public BigDecimal getPltCubngIndic() {
		return this.pltCubngIndic;
	}

	public void setPltCubngIndic(BigDecimal pltCubngIndic) {
		this.pltCubngIndic = pltCubngIndic;
	}

	public String getPltzOrd() {
		return this.pltzOrd;
	}

	public void setPltzOrd(String pltzOrd) {
		this.pltzOrd = pltzOrd;
	}

	public String getPnhCtrlNbr() {
		return this.pnhCtrlNbr;
	}

	public void setPnhCtrlNbr(String pnhCtrlNbr) {
		this.pnhCtrlNbr = pnhCtrlNbr;
	}

	public String getPnhFlag() {
		return this.pnhFlag;
	}

	public void setPnhFlag(String pnhFlag) {
		this.pnhFlag = pnhFlag;
	}

	public String getPoType() {
		return this.poType;
	}

	public void setPoType(String poType) {
		this.poType = poType;
	}

	public String getPortOfDischarge() {
		return this.portOfDischarge;
	}

	public void setPortOfDischarge(String portOfDischarge) {
		this.portOfDischarge = portOfDischarge;
	}

	public String getPortOfLoading() {
		return this.portOfLoading;
	}

	public void setPortOfLoading(String portOfLoading) {
		this.portOfLoading = portOfLoading;
	}

	public BigDecimal getPrePackFlag() {
		return this.prePackFlag;
	}

	public void setPrePackFlag(BigDecimal prePackFlag) {
		this.prePackFlag = prePackFlag;
	}

	public String getPreStikrCode() {
		return this.preStikrCode;
	}

	public void setPreStikrCode(String preStikrCode) {
		this.preStikrCode = preStikrCode;
	}

	public String getPrimaryMaxiAddrNbr() {
		return this.primaryMaxiAddrNbr;
	}

	public void setPrimaryMaxiAddrNbr(String primaryMaxiAddrNbr) {
		this.primaryMaxiAddrNbr = primaryMaxiAddrNbr;
	}

	public String getPrintCanadianCustInvcFlag() {
		return this.printCanadianCustInvcFlag;
	}

	public void setPrintCanadianCustInvcFlag(String printCanadianCustInvcFlag) {
		this.printCanadianCustInvcFlag = printCanadianCustInvcFlag;
	}

	public String getPrintCoo() {
		return this.printCoo;
	}

	public void setPrintCoo(String printCoo) {
		this.printCoo = printCoo;
	}

	public String getPrintDockRcptFlag() {
		return this.printDockRcptFlag;
	}

	public void setPrintDockRcptFlag(String printDockRcptFlag) {
		this.printDockRcptFlag = printDockRcptFlag;
	}

	public String getPrintInv() {
		return this.printInv;
	}

	public void setPrintInv(String printInv) {
		this.printInv = printInv;
	}

	public String getPrintNaftaCooFlag() {
		return this.printNaftaCooFlag;
	}

	public void setPrintNaftaCooFlag(String printNaftaCooFlag) {
		this.printNaftaCooFlag = printNaftaCooFlag;
	}

	public String getPrintOceanBolFlag() {
		return this.printOceanBolFlag;
	}

	public void setPrintOceanBolFlag(String printOceanBolFlag) {
		this.printOceanBolFlag = printOceanBolFlag;
	}

	public String getPrintPkgListFlag() {
		return this.printPkgListFlag;
	}

	public void setPrintPkgListFlag(String printPkgListFlag) {
		this.printPkgListFlag = printPkgListFlag;
	}

	public String getPrintSed() {
		return this.printSed;
	}

	public void setPrintSed(String printSed) {
		this.printSed = printSed;
	}

	public String getPrintShprLtrOfInstrFlag() {
		return this.printShprLtrOfInstrFlag;
	}

	public void setPrintShprLtrOfInstrFlag(String printShprLtrOfInstrFlag) {
		this.printShprLtrOfInstrFlag = printShprLtrOfInstrFlag;
	}

	public String getProNbr() {
		return this.proNbr;
	}

	public void setProNbr(String proNbr) {
		this.proNbr = proNbr;
	}

	public String getProcRtlRteRule() {
		return this.procRtlRteRule;
	}

	public void setProcRtlRteRule(String procRtlRteRule) {
		this.procRtlRteRule = procRtlRteRule;
	}

	public String getProdSchedRefNbr() {
		return this.prodSchedRefNbr;
	}

	public void setProdSchedRefNbr(String prodSchedRefNbr) {
		this.prodSchedRefNbr = prodSchedRefNbr;
	}

	public BigDecimal getProdValue() {
		return this.prodValue;
	}

	public void setProdValue(BigDecimal prodValue) {
		this.prodValue = prodValue;
	}

	public String getPrtyCode() {
		return this.prtyCode;
	}

	public void setPrtyCode(String prtyCode) {
		this.prtyCode = prtyCode;
	}

	public String getPrtySfx() {
		return this.prtySfx;
	}

	public void setPrtySfx(String prtySfx) {
		this.prtySfx = prtySfx;
	}

	public String getPrtyType() {
		return this.prtyType;
	}

	public void setPrtyType(String prtyType) {
		this.prtyType = prtyType;
	}

	public String getReplFlag() {
		return this.replFlag;
	}

	public void setReplFlag(String replFlag) {
		this.replFlag = replFlag;
	}

	public String getRteAttr() {
		return this.rteAttr;
	}

	public void setRteAttr(String rteAttr) {
		this.rteAttr = rteAttr;
	}

	public String getRteGuideNbr() {
		return this.rteGuideNbr;
	}

	public void setRteGuideNbr(String rteGuideNbr) {
		this.rteGuideNbr = rteGuideNbr;
	}

	public String getRteId() {
		return this.rteId;
	}

	public void setRteId(String rteId) {
		this.rteId = rteId;
	}

	public BigDecimal getRteLoadSeq() {
		return this.rteLoadSeq;
	}

	public void setRteLoadSeq(BigDecimal rteLoadSeq) {
		this.rteLoadSeq = rteLoadSeq;
	}

	public BigDecimal getRteStopSeq() {
		return this.rteStopSeq;
	}

	public void setRteStopSeq(BigDecimal rteStopSeq) {
		this.rteStopSeq = rteStopSeq;
	}

	public String getRteTo() {
		return this.rteTo;
	}

	public void setRteTo(String rteTo) {
		this.rteTo = rteTo;
	}

	public String getRteType1() {
		return this.rteType1;
	}

	public void setRteType1(String rteType1) {
		this.rteType1 = rteType1;
	}

	public String getRteType2() {
		return this.rteType2;
	}

	public void setRteType2(String rteType2) {
		this.rteType2 = rteType2;
	}

	public String getRteZip() {
		return this.rteZip;
	}

	public void setRteZip(String rteZip) {
		this.rteZip = rteZip;
	}

	public String getSaleGrp() {
		return this.saleGrp;
	}

	public void setSaleGrp(String saleGrp) {
		this.saleGrp = saleGrp;
	}

	public Date getSchedDlvryDate() {
		return this.schedDlvryDate;
	}

	public void setSchedDlvryDate(Date schedDlvryDate) {
		this.schedDlvryDate = schedDlvryDate;
	}

	public Date getSchedDlvryDateEnd() {
		return this.schedDlvryDateEnd;
	}

	public void setSchedDlvryDateEnd(Date schedDlvryDateEnd) {
		this.schedDlvryDateEnd = schedDlvryDateEnd;
	}

	public String getSecondaryMaxiAddrNbr() {
		return this.secondaryMaxiAddrNbr;
	}

	public void setSecondaryMaxiAddrNbr(String secondaryMaxiAddrNbr) {
		this.secondaryMaxiAddrNbr = secondaryMaxiAddrNbr;
	}

	public BigDecimal getSelRulePrty() {
		return this.selRulePrty;
	}

	public void setSelRulePrty(BigDecimal selRulePrty) {
		this.selRulePrty = selRulePrty;
	}

	public String getShipVia() {
		return this.shipVia;
	}

	public void setShipVia(String shipVia) {
		this.shipVia = shipVia;
	}

	public String getShipWCtrlNbr() {
		return this.shipWCtrlNbr;
	}

	public void setShipWCtrlNbr(String shipWCtrlNbr) {
		this.shipWCtrlNbr = shipWCtrlNbr;
	}

	public String getShipto() {
		return this.shipto;
	}

	public void setShipto(String shipto) {
		this.shipto = shipto;
	}

	public String getShiptoAddr1() {
		return this.shiptoAddr1;
	}

	public void setShiptoAddr1(String shiptoAddr1) {
		this.shiptoAddr1 = shiptoAddr1;
	}

	public String getShiptoAddr2() {
		return this.shiptoAddr2;
	}

	public void setShiptoAddr2(String shiptoAddr2) {
		this.shiptoAddr2 = shiptoAddr2;
	}

	public String getShiptoAddr3() {
		return this.shiptoAddr3;
	}

	public void setShiptoAddr3(String shiptoAddr3) {
		this.shiptoAddr3 = shiptoAddr3;
	}

	public String getShiptoCity() {
		return this.shiptoCity;
	}

	public void setShiptoCity(String shiptoCity) {
		this.shiptoCity = shiptoCity;
	}

	public String getShiptoCntry() {
		return this.shiptoCntry;
	}

	public void setShiptoCntry(String shiptoCntry) {
		this.shiptoCntry = shiptoCntry;
	}

	public String getShiptoCnty() {
		return this.shiptoCnty;
	}

	public void setShiptoCnty(String shiptoCnty) {
		this.shiptoCnty = shiptoCnty;
	}

	public String getShiptoContact() {
		return this.shiptoContact;
	}

	public void setShiptoContact(String shiptoContact) {
		this.shiptoContact = shiptoContact;
	}

	public String getShiptoName() {
		return this.shiptoName;
	}

	public void setShiptoName(String shiptoName) {
		this.shiptoName = shiptoName;
	}

	public String getShiptoState() {
		return this.shiptoState;
	}

	public void setShiptoState(String shiptoState) {
		this.shiptoState = shiptoState;
	}

	public String getShiptoWhse() {
		return this.shiptoWhse;
	}

	public void setShiptoWhse(String shiptoWhse) {
		this.shiptoWhse = shiptoWhse;
	}

	public String getShiptoZip() {
		return this.shiptoZip;
	}

	public void setShiptoZip(String shiptoZip) {
		this.shiptoZip = shiptoZip;
	}

	public String getShpmtNbr() {
		return this.shpmtNbr;
	}

	public void setShpmtNbr(String shpmtNbr) {
		this.shpmtNbr = shpmtNbr;
	}

	public String getShprId() {
		return this.shprId;
	}

	public void setShprId(String shprId) {
		this.shprId = shprId;
	}

	public String getShprOrdId() {
		return this.shprOrdId;
	}

	public void setShprOrdId(String shprOrdId) {
		this.shprOrdId = shprOrdId;
	}

	public String getSkuInvnVerf() {
		return this.skuInvnVerf;
	}

	public void setSkuInvnVerf(String skuInvnVerf) {
		this.skuInvnVerf = skuInvnVerf;
	}

	public String getSlsprsnNbr() {
		return this.slsprsnNbr;
	}

	public void setSlsprsnNbr(String slsprsnNbr) {
		this.slsprsnNbr = slsprsnNbr;
	}

	public String getSnglUnitFlag() {
		return this.snglUnitFlag;
	}

	public void setSnglUnitFlag(String snglUnitFlag) {
		this.snglUnitFlag = snglUnitFlag;
	}

	public String getSoldto() {
		return this.soldto;
	}

	public void setSoldto(String soldto) {
		this.soldto = soldto;
	}

	public String getSoldtoAddr1() {
		return this.soldtoAddr1;
	}

	public void setSoldtoAddr1(String soldtoAddr1) {
		this.soldtoAddr1 = soldtoAddr1;
	}

	public String getSoldtoAddr2() {
		return this.soldtoAddr2;
	}

	public void setSoldtoAddr2(String soldtoAddr2) {
		this.soldtoAddr2 = soldtoAddr2;
	}

	public String getSoldtoAddr3() {
		return this.soldtoAddr3;
	}

	public void setSoldtoAddr3(String soldtoAddr3) {
		this.soldtoAddr3 = soldtoAddr3;
	}

	public String getSoldtoCity() {
		return this.soldtoCity;
	}

	public void setSoldtoCity(String soldtoCity) {
		this.soldtoCity = soldtoCity;
	}

	public String getSoldtoCntry() {
		return this.soldtoCntry;
	}

	public void setSoldtoCntry(String soldtoCntry) {
		this.soldtoCntry = soldtoCntry;
	}

	public String getSoldtoName() {
		return this.soldtoName;
	}

	public void setSoldtoName(String soldtoName) {
		this.soldtoName = soldtoName;
	}

	public String getSoldtoState() {
		return this.soldtoState;
	}

	public void setSoldtoState(String soldtoState) {
		this.soldtoState = soldtoState;
	}

	public String getSoldtoZip() {
		return this.soldtoZip;
	}

	public void setSoldtoZip(String soldtoZip) {
		this.soldtoZip = soldtoZip;
	}

	public String getSplInstrCode1() {
		return this.splInstrCode1;
	}

	public void setSplInstrCode1(String splInstrCode1) {
		this.splInstrCode1 = splInstrCode1;
	}

	public String getSplInstrCode10() {
		return this.splInstrCode10;
	}

	public void setSplInstrCode10(String splInstrCode10) {
		this.splInstrCode10 = splInstrCode10;
	}

	public String getSplInstrCode2() {
		return this.splInstrCode2;
	}

	public void setSplInstrCode2(String splInstrCode2) {
		this.splInstrCode2 = splInstrCode2;
	}

	public String getSplInstrCode3() {
		return this.splInstrCode3;
	}

	public void setSplInstrCode3(String splInstrCode3) {
		this.splInstrCode3 = splInstrCode3;
	}

	public String getSplInstrCode4() {
		return this.splInstrCode4;
	}

	public void setSplInstrCode4(String splInstrCode4) {
		this.splInstrCode4 = splInstrCode4;
	}

	public String getSplInstrCode5() {
		return this.splInstrCode5;
	}

	public void setSplInstrCode5(String splInstrCode5) {
		this.splInstrCode5 = splInstrCode5;
	}

	public String getSplInstrCode6() {
		return this.splInstrCode6;
	}

	public void setSplInstrCode6(String splInstrCode6) {
		this.splInstrCode6 = splInstrCode6;
	}

	public String getSplInstrCode7() {
		return this.splInstrCode7;
	}

	public void setSplInstrCode7(String splInstrCode7) {
		this.splInstrCode7 = splInstrCode7;
	}

	public String getSplInstrCode8() {
		return this.splInstrCode8;
	}

	public void setSplInstrCode8(String splInstrCode8) {
		this.splInstrCode8 = splInstrCode8;
	}

	public String getSplInstrCode9() {
		return this.splInstrCode9;
	}

	public void setSplInstrCode9(String splInstrCode9) {
		this.splInstrCode9 = splInstrCode9;
	}

	public BigDecimal getSrlNbrTrkFlag() {
		return this.srlNbrTrkFlag;
	}

	public void setSrlNbrTrkFlag(BigDecimal srlNbrTrkFlag) {
		this.srlNbrTrkFlag = srlNbrTrkFlag;
	}

	public Date getStartShipDate() {
		return this.startShipDate;
	}

	public void setStartShipDate(Date startShipDate) {
		this.startShipDate = startShipDate;
	}

	public Date getStopShipDate() {
		return this.stopShipDate;
	}

	public void setStopShipDate(Date stopShipDate) {
		this.stopShipDate = stopShipDate;
	}

	public String getStopShipRule() {
		return this.stopShipRule;
	}

	public void setStopShipRule(String stopShipRule) {
		this.stopShipRule = stopShipRule;
	}

	public String getStoreNbr() {
		return this.storeNbr;
	}

	public void setStoreNbr(String storeNbr) {
		this.storeNbr = storeNbr;
	}

	public String getStoreType() {
		return this.storeType;
	}

	public void setStoreType(String storeType) {
		this.storeType = storeType;
	}

	public BigDecimal getSwcNbrSeq() {
		return this.swcNbrSeq;
	}

	public void setSwcNbrSeq(BigDecimal swcNbrSeq) {
		this.swcNbrSeq = swcNbrSeq;
	}

	public String getTelNbr() {
		return this.telNbr;
	}

	public void setTelNbr(String telNbr) {
		this.telNbr = telNbr;
	}

	public String getTempZone() {
		return this.tempZone;
	}

	public void setTempZone(String tempZone) {
		this.tempZone = tempZone;
	}

	public String getTermsCode() {
		return this.termsCode;
	}

	public void setTermsCode(String termsCode) {
		this.termsCode = termsCode;
	}

	public String getTermsDesc() {
		return this.termsDesc;
	}

	public void setTermsDesc(String termsDesc) {
		this.termsDesc = termsDesc;
	}

	public BigDecimal getTermsPcnt() {
		return this.termsPcnt;
	}

	public void setTermsPcnt(BigDecimal termsPcnt) {
		this.termsPcnt = termsPcnt;
	}

	public String getTerrCode() {
		return this.terrCode;
	}

	public void setTerrCode(String terrCode) {
		this.terrCode = terrCode;
	}

	public String getThrdPartyBill() {
		return this.thrdPartyBill;
	}

	public void setThrdPartyBill(String thrdPartyBill) {
		this.thrdPartyBill = thrdPartyBill;
	}

	public String getTmsOrdType() {
		return this.tmsOrdType;
	}

	public void setTmsOrdType(String tmsOrdType) {
		this.tmsOrdType = tmsOrdType;
	}

	public String getTmsPoFlag() {
		return this.tmsPoFlag;
	}

	public void setTmsPoFlag(String tmsPoFlag) {
		this.tmsPoFlag = tmsPoFlag;
	}

	public String getTmsProc() {
		return this.tmsProc;
	}

	public void setTmsProc(String tmsProc) {
		this.tmsProc = tmsProc;
	}

	public BigDecimal getTotalDlrsDisc() {
		return this.totalDlrsDisc;
	}

	public void setTotalDlrsDisc(BigDecimal totalDlrsDisc) {
		this.totalDlrsDisc = totalDlrsDisc;
	}

	public BigDecimal getTotalDlrsUndisc() {
		return this.totalDlrsUndisc;
	}

	public void setTotalDlrsUndisc(BigDecimal totalDlrsUndisc) {
		this.totalDlrsUndisc = totalDlrsUndisc;
	}

	public String getTransprtRespCode() {
		return this.transprtRespCode;
	}

	public void setTransprtRespCode(String transprtRespCode) {
		this.transprtRespCode = transprtRespCode;
	}

	public String getTrlrSize() {
		return this.trlrSize;
	}

	public void setTrlrSize(String trlrSize) {
		this.trlrSize = trlrSize;
	}

	public BigDecimal getTrlrStopSeqNbr() {
		return this.trlrStopSeqNbr;
	}

	public void setTrlrStopSeqNbr(BigDecimal trlrStopSeqNbr) {
		this.trlrStopSeqNbr = trlrStopSeqNbr;
	}

	public String getTrlrType() {
		return this.trlrType;
	}

	public void setTrlrType(String trlrType) {
		this.trlrType = trlrType;
	}

	public String getUnNbr() {
		return this.unNbr;
	}

	public void setUnNbr(String unNbr) {
		this.unNbr = unNbr;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getVendorNbr() {
		return this.vendorNbr;
	}

	public void setVendorNbr(String vendorNbr) {
		this.vendorNbr = vendorNbr;
	}

	public String getWaveLabelType() {
		return this.waveLabelType;
	}

	public void setWaveLabelType(String waveLabelType) {
		this.waveLabelType = waveLabelType;
	}

	public String getWhse() {
		return this.whse;
	}

	public void setWhse(String whse) {
		this.whse = whse;
	}

	public String getWhseXferFlag() {
		return this.whseXferFlag;
	}

	public void setWhseXferFlag(String whseXferFlag) {
		this.whseXferFlag = whseXferFlag;
	}

	public String getXferWhse() {
		return this.xferWhse;
	}

	public void setXferWhse(String xferWhse) {
		this.xferWhse = xferWhse;
	}

	public String getZoneSkip() {
		return this.zoneSkip;
	}

	public void setZoneSkip(String zoneSkip) {
		this.zoneSkip = zoneSkip;
	}

	public PktHdrIntrnl getPktHdrIntrnl() {
		return this.pktHdrIntrnl;
	}

	public void setPktHdrIntrnl(PktHdrIntrnl pktHdrIntrnl) {
		this.pktHdrIntrnl = pktHdrIntrnl;
	}

}