package models;

import java.io.Serializable;
import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;


/**
 * The persistent class for the PKT_HDR database table.
 * VC: Auto-generated by JPA table-to-entity generator July 30.
 * 
 */
@Entity
@Table(name="RGHI_Carrier_Pull")
@NamedQuery(name="RGHICarrierPull.findAll", query="SELECT p FROM RGHICarrierPull p")
public class RGHICarrierPull implements Serializable {
	
	private static final long serialVersionUID = 284729281L;

	@Column(name="WHSE")
	private String whse;
	
	@Column(name="SHIPTO_ZIP")
	private String shiptoZip;
	
	@Column(name="SHIP_VIA")
	private String shipVia;
	
	@Column(name="PULL_TRLR_CODE")
	private String pullTrlrCode;
	
	@Temporal(TemporalType.TIME)
	@Column(name="PULL_TIME")
	private Date pullTime;
	
	@Column(name="ANYTEXT1")
	private String anyText1;

	@Column(name="ANYNBR1")
	private String anyNbr1;

	@Temporal(TemporalType.DATE)
	@Column(name="CREATE_DATE_TIME")
	private Date createDateTime;
	
	@Temporal(TemporalType.DATE)
	@Column(name="MOD_DATE_TIME")
	private Date modDateTime;
	
	@Column(name="USER_ID")
	private String userId;

	public String getWhse() {
		return whse;
	}

	public void setWhse(String whse) {
		this.whse = whse;
	}

	public String getShiptoZip() {
		return shiptoZip;
	}

	public void setShiptoZip(String shiptoZip) {
		this.shiptoZip = shiptoZip;
	}

	public String getShipVia() {
		return shipVia;
	}

	public void setShipVia(String shipVia) {
		this.shipVia = shipVia;
	}

	public String getPullTrlrCode() {
		return pullTrlrCode;
	}

	public void setPullTrlrCode(String pullTrlrCode) {
		this.pullTrlrCode = pullTrlrCode;
	}

	public Date getPullTime() {
		return pullTime;
	}

	public void setPullTime(Date pullTime) {
		this.pullTime = pullTime;
	}

	public String getAnyText1() {
		return anyText1;
	}

	public void setAnyText1(String anyText1) {
		this.anyText1 = anyText1;
	}

	public String getAnyNbr1() {
		return anyNbr1;
	}

	public void setAnyNbr1(String anyNbr1) {
		this.anyNbr1 = anyNbr1;
	}

	public Date getCreateDateTime() {
		return createDateTime;
	}

	public void setCreateDateTime(Date createDateTime) {
		this.createDateTime = createDateTime;
	}

	public Date getModDateTime() {
		return modDateTime;
	}

	public void setModDateTime(Date modDateTime) {
		this.modDateTime = modDateTime;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}



	

}